"""
Network Configuration Intent Generator for 6G Digital Immunity Simulation.

Transforms RCA anomaly reports into structured configuration intents (CUE/YAML)
that are submitted to the Deterministic Security Framework (DSF) for validation.

Architecture Context:
    The TelcoLLM Agent generates intents based on detected anomalies.  These
    intents describe *what* parameter changes are needed and *why*, without
    prescribing *how* the DSF validates them.  The DSF independently verifies
    safety guarantees (CBF, Lyapunov, Zeno-freeness, CUE compliance).

Dependencies:
    - numpy (for confidence computation helpers)

Usage:
    from llm_agent.intent.config_generator import ConfigGenerator

    generator = ConfigGenerator()
    intent = generator.generate_intent(anomalies)
    # intent is an IntentPayload ready for gRPC submission
"""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import numpy as np

# Import Anomaly from the RCA chain module
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from inference.rca_chain import Anomaly, AnomalyType, Severity  # noqa: E402
from core.llm_client import TelcoLLMClient  # noqa: E402

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants / Intent Categories
# ---------------------------------------------------------------------------

INTENT_CATEGORIES = [
    "RADIO_OPTIMIZATION",
    "BEARER_QOS_ADJUSTMENT",
    "RESOURCE_MANAGEMENT",
    "HANDOVER_TUNING",
    "INTERFERENCE_MITIGATION",
    "COMPOSITE_REMEDIATION",
]

DEFAULT_SAFETY_MARGINS: dict[str, dict[str, float]] = {
    "tx_power_dbm": {"min": 5.0, "max": 46.0, "step": 1.0},
    "antenna_tilt_deg": {"min": -15.0, "max": 15.0, "step": 1.0},
    "cell_reselection_offset_db": {"min": 0.0, "max": 24.0, "step": 2.0},
    "a3_offset_db": {"min": 0.0, "max": 15.0, "step": 1.0},
    "ho_hysteresis_db": {"min": 0.0, "max": 10.0, "step": 0.5},
    "time_to_trigger_ms": {"min": 0, "max": 5120, "step": 128},
    "mbr_bps": {"min": 0, "max": 1_000_000_000, "step": 1_000_000},
    "gbr_bps": {"min": 0, "max": 100_000_000, "step": 100_000},
    "session_limit": {"min": 1, "max": 65535, "step": 1},
    "tunnel_limit": {"min": 1, "max": 65535, "step": 1},
    "qci": {"min": 1, "max": 9, "step": 1},
    "arp_priority": {"min": 1, "max": 15, "step": 1},
}

DEFAULT_ELEMENT_TYPE_MAP: dict[str, str] = {
    "eNB": "RAN",
    "gNB": "RAN",
    "enodeb": "RAN",
    "gnodeb": "RAN",
    "MME": "CORE",
    "AMF": "CORE",
    "SGW": "CORE",
    "UPF": "CORE",
    "PGW": "CORE",
    "SMF": "CORE",
}


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------


@dataclass
class IntentPayload:
    """Structured configuration intent generated by the TelcoLLM Agent.

    This payload is serialised to the NetworkIntent protobuf message before
    submission to the DSF via gRPC.

    Attributes:
        intent_id:         Unique identifier for this intent instance.
        rationale:         Human-readable explanation of why this intent was generated.
        generated_at:      ISO-8601 timestamp of intent creation.
        target_element_id: The network element to be reconfigured.
        category:          Intent category (e.g. RADIO_OPTIMIZATION).
        confidence_score:  Confidence of the proposed changes [0.0, 1.0].
        radio_params:      Proposed radio access parameter changes.
        core_params:       Proposed core network parameter changes.
        transport_params:  Proposed transport layer parameter changes.
        security_params:   Proposed security parameter changes.
        reasoning_trace:   Step-by-step trace of the decision process.
        metadata:          Additional context metadata (source anomalies, etc.).
    """

    intent_id: str = ""
    rationale: str = ""
    generated_at: str = ""
    target_element_id: str = ""
    category: str = "RADIO_OPTIMIZATION"
    confidence_score: float = 0.0
    radio_params: dict[str, Any] = field(default_factory=dict)
    core_params: dict[str, Any] = field(default_factory=dict)
    transport_params: dict[str, Any] = field(default_factory=dict)
    security_params: dict[str, Any] = field(default_factory=dict)
    reasoning_trace: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.intent_id:
            self.intent_id = f"intent-{uuid.uuid4().hex[:16]}"
        if not self.generated_at:
            self.generated_at = datetime.now(timezone.utc).isoformat()


@dataclass
class ConfigGeneratorConfig:
    """Configuration for the intent generator.

    Attributes:
        element_id_to_type_map: Mapping from element ID prefix to element type
                                 (RAN, CORE, TRANSPORT).
        safety_margins:          Per-parameter safety bounds for constraining
                                 proposed values.
        intent_cooldown_s:       Minimum seconds between intent submissions for
                                 the same element to prevent oscillation.
    """

    element_id_to_type_map: dict[str, str] = field(
        default_factory=lambda: dict(DEFAULT_ELEMENT_TYPE_MAP)
    )
    safety_margins: dict[str, dict[str, float]] = field(
        default_factory=lambda: dict(DEFAULT_SAFETY_MARGINS)
    )
    intent_cooldown_s: float = 5.0


# ---------------------------------------------------------------------------
# Intent Generator
# ---------------------------------------------------------------------------


class ConfigGenerator:
    """Generates network configuration intents from RCA anomaly reports.

    The generator analyses detected anomalies, determines appropriate parameter
    changes, applies safety margins, and produces an :class:`IntentPayload`
    suitable for DSF submission.

    Intent generation rules:
        - RADIO_DEGRADATION  → TX power increase, antenna tilt adjustment
        - HANDOVER_FAILURE   → HO hysteresis / time-to-trigger adjustment
        - INTERFERENCE       → Cell reselection offset, A3 offset adjustment
        - BEARER_FAILURE     → QoS profile changes, MBR/GBR adjustments
        - RESOURCE_EXHAUSTION → Session limits, tunnel limits
        - SIGNALING_STORM    → Rate limiting parameters
        - LATENCY_SPIKE      → Transport parameter changes

    Args:
        config: Optional generator configuration.
    """

    def __init__(self, config: ConfigGeneratorConfig | None = None) -> None:
        self._config = config or ConfigGeneratorConfig()
        self._last_intent_times: dict[str, float] = {}
        self.llm_client = TelcoLLMClient()
        logger.info("ConfigGenerator initialised with TelcoLLMClient")

    def generate_intent(
        self,
        anomalies: list[Anomaly],
        current_state: dict[str, Any] | None = None,
    ) -> IntentPayload:
        """Generate a configuration intent from a list of detected anomalies.

        Process:
        1. Classify anomalies by type and determine intent category.
        2. Generate per-anomaly-type parameter changes.
        3. Merge all parameter changes into a single intent.
        4. Apply safety margins.
        5. Compute confidence score.
        6. Build rationale and reasoning trace.

        Args:
            anomalies:     List of anomalies from the RCA engine.
            current_state: Optional current configuration state for context.

        Returns:
            Fully populated :class:`IntentPayload`.
        """
        if not anomalies:
            logger.warning("generate_intent called with empty anomaly list")
            return IntentPayload(
                rationale="No anomalies detected; no intent generated.",
                confidence_score=0.0,
                category="NO_ACTION",
            )

        logger.info(
            "Generating intent from %d anomalies",
            len(anomalies),
        )

        # Determine target element (use the most-cited element)
        target_element = self._determine_target_element(anomalies)
        category = self._determine_category(anomalies)

        # Generate parameter changes per anomaly
        all_radio_params: dict[str, Any] = {}
        all_core_params: dict[str, Any] = {}
        all_transport_params: dict[str, Any] = {}
        all_security_params: dict[str, Any] = {}
        reasoning_trace: list[dict[str, Any]] = []
        change_sources: list[dict[str, Any]] = []

        # Build telemetry for LLM
        telemetry_data = {}
        for anomaly in anomalies:
            if anomaly.metrics_snapshot:
                telemetry_data.update(anomaly.metrics_snapshot)

        # 1) Try LLM First
        llm_intent_json = self.llm_client.generate_intent(telemetry_data)
        if llm_intent_json:
            category = llm_intent_json.get("category", category)
            confidence = float(llm_intent_json.get("confidence_score", 0.90))
            if "tx_power_dbm" in llm_intent_json:
                all_radio_params["tx_power_adjustment_dbm"] = llm_intent_json[
                    "tx_power_dbm"
                ]
            if "ho_hysteresis_db" in llm_intent_json:
                all_radio_params["ho_hysteresis_adjustment_db"] = llm_intent_json[
                    "ho_hysteresis_db"
                ]
            rationale_llm = llm_intent_json.get("rationale", "")

            # Fast track LLM intent
            intent = IntentPayload(
                target_element_id=target_element,
                category=category,
                confidence_score=confidence,
                radio_params=all_radio_params,
                rationale=rationale_llm,
                metadata={
                    "source_anomalies": [{"id": a.anomaly_id for a in anomalies}]
                },
            )
            logger.info(f"LLM Generated Intent: {intent.intent_id}")
            return intent

        # 2) Fallback to Rule-based
        for anomaly in anomalies:
            trace_step: dict[str, Any] = {
                "step": len(reasoning_trace) + 1,
                "anomaly_id": anomaly.anomaly_id,
                "anomaly_type": anomaly.anomaly_type.value,
                "severity": anomaly.severity.value,
                "action": "Analyzing anomaly",
            }

            try:
                if anomaly.anomaly_type in (
                    AnomalyType.RADIO_DEGRADATION,
                    AnomalyType.HANDOVER_FAILURE,
                    AnomalyType.INTERFERENCE,
                ):
                    radio_changes = self._generate_radio_intent(anomaly)
                    all_radio_params.update(radio_changes)
                    trace_step["radio_changes"] = radio_changes
                    trace_step["action"] = "Generated radio parameter adjustments"

                elif anomaly.anomaly_type in (
                    AnomalyType.BEARER_FAILURE,
                    AnomalyType.LATENCY_SPIKE,
                ):
                    bearer_changes = self._generate_bearer_intent(anomaly)
                    all_core_params.update(bearer_changes)
                    trace_step["bearer_changes"] = bearer_changes
                    trace_step["action"] = "Generated bearer QoS adjustments"

                elif anomaly.anomaly_type in (AnomalyType.RESOURCE_EXHAUSTION,):
                    resource_changes = self._generate_resource_intent(anomaly)
                    all_core_params.update(resource_changes)
                    trace_step["resource_changes"] = resource_changes
                    trace_step["action"] = "Generated resource management parameters"

                elif anomaly.anomaly_type == AnomalyType.SIGNALING_STORM:
                    storm_changes = self._generate_signaling_intent(anomaly)
                    all_security_params.update(storm_changes)
                    trace_step["security_changes"] = storm_changes
                    trace_step["action"] = "Generated signalling rate limit parameters"

                else:
                    trace_step["action"] = (
                        f"No parameter mapping for {anomaly.anomaly_type.value}"
                    )

            except Exception as exc:
                logger.error(
                    "Error generating intent for anomaly %s: %s",
                    anomaly.anomaly_id,
                    exc,
                    exc_info=True,
                )
                trace_step["error"] = str(exc)
                trace_step["action"] = "Error during parameter generation"

            reasoning_trace.append(trace_step)

        # Record change sources for auditability
        change_sources = [
            {
                "anomaly_id": a.anomaly_id,
                "anomaly_type": a.anomaly_type.value,
                "severity": a.severity.value,
                "confidence": a.confidence,
                "description": a.description,
            }
            for a in anomalies
        ]

        # Apply safety margins to all parameter dicts
        all_radio_params = self._apply_safety_margins(
            all_radio_params, self._config.safety_margins
        )
        all_core_params = self._apply_safety_margins(
            all_core_params, self._config.safety_margins
        )
        all_transport_params = self._apply_safety_margins(
            all_transport_params, self._config.safety_margins
        )

        # Compute confidence
        all_changes = {
            **all_radio_params,
            **all_core_params,
            **all_transport_params,
            **all_security_params,
        }
        confidence = self._compute_confidence(anomalies, all_changes)

        # Build rationale
        rationale = self._build_rationale(anomalies, all_changes)

        # Build final reasoning trace with summary
        reasoning_trace.append(
            {
                "step": len(reasoning_trace) + 1,
                "action": "Intent generation complete",
                "category": category,
                "total_changes": len(all_changes),
                "confidence": confidence,
                "safety_margins_applied": True,
            }
        )

        # Cooldown check
        now = __import__("time").time()
        last_time = self._last_intent_times.get(target_element, 0.0)
        if now - last_time < self._config.intent_cooldown_s:
            logger.warning(
                "Intent cooldown active for %s (%.1fs remaining)",
                target_element,
                self._config.intent_cooldown_s - (now - last_time),
            )

        intent = IntentPayload(
            target_element_id=target_element,
            category=category,
            confidence_score=confidence,
            radio_params=all_radio_params,
            core_params=all_core_params,
            transport_params=all_transport_params,
            security_params=all_security_params,
            rationale=rationale,
            reasoning_trace=reasoning_trace,
            metadata={
                "source_anomaly_count": len(anomalies),
                "source_anomalies": change_sources,
                "current_state": current_state or {},
                "cooldown_remaining_s": max(
                    0.0,
                    self._config.intent_cooldown_s - (now - last_time),
                ),
            },
        )

        self._last_intent_times[target_element] = now

        logger.info(
            "Intent generated: %s (category=%s, confidence=%.3f, "
            "radio_changes=%d, core_changes=%d)",
            intent.intent_id,
            category,
            confidence,
            len(all_radio_params),
            len(all_core_params),
        )

        return intent

    # ---- Radio Intent Generation ---------------------------------------------

    def _generate_radio_intent(self, anomaly: Anomaly) -> dict[str, Any]:
        """Map a radio-related anomaly to specific radio parameter changes.

        Mapping rules:
            - RADIO_DEGRADATION → tx_power_dbm increase, antenna_tilt_deg adjustment
            - HANDOVER_FAILURE   → ho_hysteresis_db, time_to_trigger_ms
            - INTERFERENCE       → cell_reselection_offset_db, a3_offset_db

        Args:
            anomaly: The radio-related anomaly.

        Returns:
            Dictionary of proposed parameter changes.
        """
        changes: dict[str, Any] = {}
        snapshot = anomaly.metrics_snapshot or {}

        if anomaly.anomaly_type == AnomalyType.RADIO_DEGRADATION:
            metric_value = snapshot.get("value", 0.0)
            metric_name = snapshot.get("metric", "unknown")

            # TX power boost proportional to degradation
            if metric_name in ("rsrp", "rsrq", "sinr"):
                degradation_factor = min(1.0, abs(float(metric_value)) / 100.0)
                tx_power_boost = round(degradation_factor * 10.0)  # up to +10 dBm
                if tx_power_boost > 0:
                    changes["tx_power_adjustment_dbm"] = tx_power_boost

                # Antenna tilt adjustment for coverage issues
                if metric_name == "rsrp" and float(metric_value) < -105.0:
                    changes["antenna_tilt_adjustment_deg"] = -2.0  # downtilt to focus

            # RSRP volatility → prepare handover adjustments
            if metric_name == "rsrp_volatility":
                std_dev = snapshot.get("std_dev", 0.0)
                if float(std_dev) > 5.0:
                    changes["ho_hysteresis_adjustment_db"] = 2.0
                    changes["time_to_trigger_adjustment_ms"] = 256

        elif anomaly.anomaly_type == AnomalyType.HANDOVER_FAILURE:
            ho_rate = snapshot.get("value", 0.0)

            # High HO rate → increase hysteresis to reduce ping-pong
            if float(ho_rate) > 20.0:
                changes["ho_hysteresis_adjustment_db"] = 3.0
                changes["time_to_trigger_adjustment_ms"] = 512
            elif float(ho_rate) > 10.0:
                changes["ho_hysteresis_adjustment_db"] = 1.5
                changes["time_to_trigger_adjustment_ms"] = 256

            # Low HO success rate → adjust offsets
            metric_name = snapshot.get("metric", "")
            if metric_name == "ho_success_rate":
                changes["a3_offset_adjustment_db"] = 2.0
                changes["time_to_trigger_adjustment_ms"] = 128

            # Reselection failure → cell reselection offset
            metric_name = snapshot.get("metric", "")
            if metric_name == "reselection_failure_rate":
                changes["cell_reselection_offset_adjustment_db"] = 4.0

        elif anomaly.anomaly_type == AnomalyType.INTERFERENCE:
            noise_floor = snapshot.get("value", -100.0)
            nf = float(noise_floor)

            # Higher noise floor → larger reselection offset to push UEs away
            if nf > -90.0:
                offset_boost = round((nf + 90.0) / 2.0)  # proportional to severity
                changes["cell_reselection_offset_adjustment_db"] = max(
                    2.0, offset_boost
                )
                changes["a3_offset_adjustment_db"] = max(1.0, offset_boost / 2.0)

            # Also increase TX power to maintain signal quality
            changes["tx_power_adjustment_dbm"] = 3.0

        logger.debug(
            "Radio intent changes for %s: %s",
            anomaly.anomaly_type.value,
            changes,
        )
        return changes

    # ---- Bearer Intent Generation --------------------------------------------

    def _generate_bearer_intent(self, anomaly: Anomaly) -> dict[str, Any]:
        """Map bearer-related anomalies to QoS / bearer parameter changes.

        Args:
            anomaly: The bearer-related anomaly.

        Returns:
            Dictionary of proposed parameter changes.
        """
        changes: dict[str, Any] = {}
        snapshot = anomaly.metrics_snapshot or {}

        if anomaly.anomaly_type == AnomalyType.BEARER_FAILURE:
            metric_name = snapshot.get("metric", "")
            metric_value = float(snapshot.get("value", 0.0))

            if metric_name == "packet_loss_rate":
                # High packet loss → reduce MBR to avoid congestion
                if metric_value > 0.10:
                    changes["mbr_reduction_percent"] = 30.0
                    changes["qci_adjustment"] = 1  # Lower priority QCI
                elif metric_value > 0.05:
                    changes["mbr_reduction_percent"] = 15.0

                # Also adjust ARP to allow preemption of low-priority bearers
                if metric_value > 0.08:
                    changes["arp_priority_boost"] = 2

            elif metric_name == "throughput_drop":
                drop_ratio = float(snapshot.get("drop_ratio", 0.0))
                if drop_ratio > 0.50:
                    # Significant drop → allocate guaranteed resources
                    changes["gbr_increase_percent"] = 50.0
                    changes["arp_priority_boost"] = 3
                elif drop_ratio > 0.25:
                    changes["gbr_increase_percent"] = 25.0

            elif metric_name == "bearer_setup_failure_rate":
                # High setup failure → increase session timeout
                changes["session_timeout_adjustment_ms"] = 5000
                changes["max_retransmission_increase"] = 2

        elif anomaly.anomalyType == AnomalyType.LATENCY_SPIKE:
            rtt = float(snapshot.get("value", 0.0))
            if rtt > 200.0:
                changes["mbr_reduction_percent"] = 40.0
                changes["session_timeout_adjustment_ms"] = 10000
            elif rtt > 100.0:
                changes["mbr_reduction_percent"] = 20.0
                changes["session_timeout_adjustment_ms"] = 5000

        # Handle LATENCY_SPIKE with corrected reference
        if anomaly.anomaly_type == AnomalyType.LATENCY_SPIKE:
            rtt = float(snapshot.get("value", 0.0))
            if rtt > 200.0:
                changes["mbr_reduction_percent"] = 40.0
                changes["session_timeout_adjustment_ms"] = 10000
            elif rtt > 100.0:
                changes["mbr_reduction_percent"] = 20.0
                changes["session_timeout_adjustment_ms"] = 5000

        logger.debug(
            "Bearer intent changes for %s: %s",
            anomaly.anomaly_type.value,
            changes,
        )
        return changes

    # ---- Resource Intent Generation ------------------------------------------

    def _generate_resource_intent(self, anomaly: Anomaly) -> dict[str, Any]:
        """Map resource anomalies to session / tunnel management parameters.

        Args:
            anomaly: The resource-related anomaly.

        Returns:
            Dictionary of proposed parameter changes.
        """
        changes: dict[str, Any] = {}
        snapshot = anomaly.metrics_snapshot or {}
        metric_name = snapshot.get("metric", "")
        metric_value = float(snapshot.get("value", 0.0))

        if metric_name == "cpu_utilization":
            if metric_value > 0.95:
                # Critical CPU → aggressively reduce load
                changes["session_limit_reduction_percent"] = 40.0
                changes["tunnel_limit_reduction_percent"] = 30.0
                changes["enable_load_shedding"] = True
            elif metric_value > 0.90:
                changes["session_limit_reduction_percent"] = 20.0
                changes["tunnel_limit_reduction_percent"] = 15.0

        elif metric_name == "memory_utilization":
            if metric_value > 0.90:
                changes["session_limit_reduction_percent"] = 30.0
                changes["idle_session_timeout_ms"] = 5000
            elif metric_value > 0.85:
                changes["session_limit_reduction_percent"] = 15.0
                changes["idle_session_timeout_ms"] = 10000

        elif metric_name == "temperature_c":
            if metric_value > 85.0:
                changes["session_limit_reduction_percent"] = 50.0
                changes["enable_thermal_throttle"] = True
            elif metric_value > 70.0:
                changes["session_limit_reduction_percent"] = 20.0

        elif metric_name == "gtpu_tunnel_utilization":
            if metric_value > 0.95:
                changes["tunnel_limit_reduction_percent"] = 25.0
                changes["enable_tunnel_cleanup"] = True
            elif metric_value > 0.85:
                changes["tunnel_limit_reduction_percent"] = 10.0

        logger.debug(
            "Resource intent changes: %s",
            changes,
        )
        return changes

    # ---- Signaling Intent Generation -----------------------------------------

    def _generate_signaling_intent(self, anomaly: Anomaly) -> dict[str, Any]:
        """Map signaling storm anomaly to rate-limiting parameters.

        Args:
            anomaly: The signaling storm anomaly.

        Returns:
            Dictionary of proposed parameter changes.
        """
        changes: dict[str, Any] = {
            "signaling_rate_limit_per_sec": 100,
            "signaling_burst_allowance": 10,
            "enable_signaling_throttle": True,
            "max_signaling_retries": 3,
            "signaling_backoff_base_ms": 1000,
        }

        if anomaly.severity == Severity.CRITICAL:
            changes["signaling_rate_limit_per_sec"] = 50
            changes["enable_signaling_blacklist"] = True

        logger.debug("Signaling intent changes: %s", changes)
        return changes

    # ---- Category Determination ----------------------------------------------

    def _determine_category(self, anomalies: list[Anomaly]) -> str:
        """Select the most appropriate intent category based on anomaly types.

        Args:
            anomalies: List of anomalies to classify.

        Returns:
            Intent category string.
        """
        type_set = {a.anomaly_type for a in anomalies}

        # Composite if multiple unrelated types
        if len(type_set) >= 3:
            return "COMPOSITE_REMEDIATION"

        # Interference-specific
        if AnomalyType.INTERFERENCE in type_set:
            return "INTERFERENCE_MITIGATION"

        # Handover-specific
        if AnomalyType.HANDOVER_FAILURE in type_set and len(type_set) == 1:
            return "HANDOVER_TUNING"

        # Radio-only
        if AnomalyType.RADIO_DEGRADATION in type_set and len(type_set) == 1:
            return "RADIO_OPTIMIZATION"

        # Bearer-specific
        if (
            AnomalyType.BEARER_FAILURE in type_set
            or AnomalyType.LATENCY_SPIKE in type_set
        ):
            if len(type_set) == 1:
                return "BEARER_QOS_ADJUSTMENT"

        # Resource-specific
        if AnomalyType.RESOURCE_EXHAUSTION in type_set and len(type_set) == 1:
            return "RESOURCE_MANAGEMENT"

        # Signaling
        if AnomalyType.SIGNALING_STORM in type_set:
            return "COMPOSITE_REMEDIATION"

        # Default
        return "COMPOSITE_REMEDIATION"

    # ---- Target Element Selection --------------------------------------------

    def _determine_target_element(self, anomalies: list[Anomaly]) -> str:
        """Determine the target element for the intent.

        Uses the most frequently cited element_id, falling back to the first.

        Args:
            anomalies: List of anomalies.

        Returns:
            Element ID string.
        """
        if not anomalies:
            return "unknown"

        counts: dict[str, int] = {}
        for a in anomalies:
            counts[a.element_id] = counts.get(a.element_id, 0) + 1

        # Sort by count descending, then by severity
        sorted_elements = sorted(
            counts.items(),
            key=lambda x: (
                x[1],
                self._severity_weight(
                    next(a.severity for a in anomalies if a.element_id == x[0])
                ),
            ),
            reverse=True,
        )

        return sorted_elements[0][0]

    # ---- Confidence Computation ---------------------------------------------

    def _compute_confidence(
        self,
        anomalies: list[Anomaly],
        proposed_changes: dict[str, Any],
    ) -> float:
        """Compute overall confidence score for the proposed intent.

        Factors:
        - Mean anomaly confidence (weight: 0.4)
        - Severity weighting (weight: 0.2)
        - Parameter change magnitude penalty (weight: 0.2)
        - Source anomaly count penalty (weight: 0.1)
        - Category specificity bonus (weight: 0.1)

        Args:
            anomalies:         Source anomalies.
            proposed_changes: Dictionary of all proposed parameter changes.

        Returns:
            Confidence score in [0.0, 1.0].
        """
        if not anomalies:
            return 0.0

        # Factor 1: Mean anomaly confidence
        mean_confidence = np.mean([a.confidence for a in anomalies])

        # Factor 2: Severity weighting
        severity_weights = {
            Severity.LOW: 0.3,
            Severity.MEDIUM: 0.6,
            Severity.HIGH: 0.85,
            Severity.CRITICAL: 1.0,
        }
        mean_severity = np.mean(
            [severity_weights.get(a.severity, 0.5) for a in anomalies]
        )

        # Factor 3: Change magnitude penalty
        # Larger changes → lower confidence (more risky)
        change_magnitude = 0.0
        len(proposed_changes)
        for key, value in proposed_changes.items():
            if isinstance(value, (int, float)):
                change_magnitude += abs(float(value))
            elif isinstance(value, bool) and value:
                change_magnitude += 1.0
        magnitude_penalty = 1.0 - min(0.5, change_magnitude / 50.0)

        # Factor 4: Multi-anomaly penalty
        count_penalty = max(0.5, 1.0 - (len(anomalies) - 1) * 0.15)

        # Factor 5: Category specificity bonus
        type_set = {a.anomaly_type for a in anomalies}
        specificity = 1.0 if len(type_set) == 1 else 0.7

        # Weighted combination
        confidence = (
            0.4 * mean_confidence
            + 0.2 * mean_severity
            + 0.2 * magnitude_penalty
            + 0.1 * count_penalty
            + 0.1 * specificity
        )

        confidence = float(np.clip(confidence, 0.0, 1.0))

        logger.debug(
            "Confidence computation: mean_conf=%.3f, severity=%.3f, "
            "mag_penalty=%.3f, count_penalty=%.3f, specificity=%.3f → %.3f",
            mean_confidence,
            mean_severity,
            magnitude_penalty,
            count_penalty,
            specificity,
            confidence,
        )

        return confidence

    # ---- Rationale Builder ---------------------------------------------------

    def _build_rationale(
        self,
        anomalies: list[Anomaly],
        changes: dict[str, Any],
    ) -> str:
        """Build a human-readable rationale explaining the proposed intent.

        Args:
            anomalies: Source anomalies.
            changes:   Proposed parameter changes.

        Returns:
            Multi-line rationale string.
        """
        lines: list[str] = []

        # Summary
        element_ids = list({a.element_id for a in anomalies})
        anomaly_types = [a.anomaly_type.value for a in anomalies]
        severity_counts: dict[str, int] = {}
        for a in anomalies:
            s = a.severity.value
            severity_counts[s] = severity_counts.get(s, 0) + 1

        lines.append(
            f"Intent generated in response to {len(anomalies)} detected anomaly(ies) "
            f"on element(s) {', '.join(element_ids)}."
        )
        lines.append(
            f"Anomaly types: {', '.join(anomaly_types)}. "
            f"Severity distribution: {severity_counts}."
        )

        # Per-anomaly descriptions
        for a in anomalies:
            lines.append(
                f"  - [{a.severity.value.upper()}] {a.anomaly_type.value}: "
                f"{a.description} (confidence={a.confidence:.2f})"
            )

        # Proposed changes summary
        if changes:
            lines.append(f"Proposed {len(changes)} parameter adjustment(s):")
            for key, value in changes.items():
                lines.append(f"  - {key}: {value}")

        rationale = "\n".join(lines)
        return rationale

    # ---- Reasoning Trace Builder ---------------------------------------------

    def _build_reasoning_trace(
        self,
        anomalies: list[Anomaly],
        changes: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """Build a detailed reasoning trace for auditability.

        Each entry in the trace represents a decision step in the intent
        generation process.

        Args:
            anomalies: Source anomalies.
            changes:   Proposed parameter changes.

        Returns:
            List of reasoning trace steps.
        """
        trace: list[dict[str, Any]] = []

        trace.append(
            {
                "step": 1,
                "action": "input_analysis",
                "detail": f"Received {len(anomalies)} anomaly reports",
                "anomaly_ids": [a.anomaly_id for a in anomalies],
                "anomaly_types": [a.anomaly_type.value for a in anomalies],
            }
        )

        trace.append(
            {
                "step": 2,
                "action": "element_targeting",
                "detail": "Target element selected based on anomaly frequency",
                "target_elements": list({a.element_id for a in anomalies}),
            }
        )

        trace.append(
            {
                "step": 3,
                "action": "category_classification",
                "detail": "Intent category determined from anomaly type analysis",
            }
        )

        trace.append(
            {
                "step": 4,
                "action": "parameter_generation",
                "detail": f"Generated {len(changes)} parameter changes",
                "change_summary": {k: v for k, v in changes.items()},
            }
        )

        trace.append(
            {
                "step": 5,
                "action": "safety_application",
                "detail": "Safety margins applied to all proposed parameters",
                "safety_bounds": self._config.safety_margins,
            }
        )

        trace.append(
            {
                "step": 6,
                "action": "confidence_computation",
                "detail": "Confidence score computed from multi-factor analysis",
            }
        )

        trace.append(
            {
                "step": 7,
                "action": "intent_finalization",
                "detail": "Intent payload finalized and ready for DSF submission",
            }
        )

        return trace

    # ---- Safety Margin Application -------------------------------------------

    def _apply_safety_margins(
        self,
        params: dict[str, Any],
        margins: dict[str, dict[str, float]],
    ) -> dict[str, Any]:
        """Constrain proposed parameter values within safety envelopes.

        For each parameter:
        - If a safety bound exists for the key, clamp the value to [min, max].
        - Round to the nearest step size.
        - If no safety bound exists, pass through unchanged.

        Args:
            params:  Proposed parameter changes.
            margins: Safety margin definitions.

        Returns:
            Safety-constrained parameter changes.
        """
        constrained: dict[str, Any] = {}

        for key, value in params.items():
            # Try to find a matching safety bound
            bound = self._find_safety_bound(key, margins)

            if bound is not None and isinstance(value, (int, float)):
                value_f = float(value)
                min_val = bound["min"]
                max_val = bound["max"]
                step = bound["step"]

                # Clamp to bounds
                clamped = max(min_val, min(max_val, value_f))

                # Round to step size
                if step > 0:
                    clamped = round(clamped / step) * step

                # Re-convert to int if original was int and step is integer
                if isinstance(value, int) and step == int(step):
                    clamped = int(clamped)

                if clamped != value_f:
                    logger.debug(
                        "Safety clamp applied to %s: %.4f → %.4f (bounds=[%.4f, %.4f])",
                        key,
                        value_f,
                        clamped,
                        min_val,
                        max_val,
                    )

                constrained[key] = clamped
            else:
                constrained[key] = value

        return constrained

    @staticmethod
    def _find_safety_bound(
        key: str,
        margins: dict[str, dict[str, float]],
    ) -> dict[str, float] | None:
        """Find a safety bound for a parameter key.

        Supports exact matches and prefix matching (e.g., "tx_power_adjustment_dbm"
        matches "tx_power_dbm").

        Args:
            key:     Parameter key to look up.
            margins: Safety margin definitions.

        Returns:
            Safety bound dict or None if no match found.
        """
        # Exact match
        if key in margins:
            return margins[key]

        # Prefix / fuzzy match
        key_lower = key.lower().replace("adjustment", "").replace("_adjustment", "")
        for margin_key, margin_val in margins.items():
            mk_lower = margin_key.lower()
            if key_lower.startswith(mk_lower) or mk_lower.startswith(key_lower):
                return margin_val

        return None

    # ---- Protobuf Serialization Helper ---------------------------------------

    def to_protobuf_dict(self, intent: IntentPayload) -> dict[str, Any]:
        """Convert an IntentPayload to a flat dictionary matching the
        ``NetworkIntent`` protobuf structure defined in ``llm_intent.proto``.

        The returned dict can be serialised to a protobuf message via
        ``NetworkIntent(**d)``.

        Args:
            intent: The IntentPayload to convert.

        Returns:
            Dictionary with keys matching the protobuf field names.
        """
        pb_dict: dict[str, Any] = {
            "intent_id": intent.intent_id,
            "rationale": intent.rationale,
            "generated_at": intent.generated_at,
            "target_element_id": intent.target_element_id,
            "category": intent.category,
            "confidence_score": intent.confidence_score,
        }

        # Radio intent parameters
        if intent.radio_params:
            pb_dict["radio_intent"] = {
                "tx_power_adjustment_dbm": intent.radio_params.get(
                    "tx_power_adjustment_dbm", 0
                ),
                "antenna_tilt_adjustment_deg": intent.radio_params.get(
                    "antenna_tilt_adjustment_deg", 0.0
                ),
                "cell_reselection_offset_db": intent.radio_params.get(
                    "cell_reselection_offset_db", 0
                ),
                "a3_offset_db": intent.radio_params.get("a3_offset_db", 0),
                "ho_hysteresis_db": intent.radio_params.get("ho_hysteresis_db", 0.0),
                "time_to_trigger_ms": intent.radio_params.get("time_to_trigger_ms", 0),
                "params": intent.radio_params,
            }

        # Core intent parameters
        if intent.core_params:
            pb_dict["core_intent"] = {
                "qci": intent.core_params.get("qci", 0),
                "mbr_bps": intent.core_params.get("mbr_bps", 0),
                "gbr_bps": intent.core_params.get("gbr_bps", 0),
                "arp_priority": intent.core_params.get("arp_priority", 0),
                "session_limit": intent.core_params.get("session_limit", 0),
                "params": intent.core_params,
            }

        # Transport intent parameters
        if intent.transport_params:
            pb_dict["transport_intent"] = {
                "params": intent.transport_params,
            }

        # Security intent parameters
        if intent.security_params:
            pb_dict["security_intent"] = {
                "params": intent.security_params,
            }

        # Reasoning trace (as JSON string for protobuf compatibility)
        if intent.reasoning_trace:
            pb_dict["reasoning_trace_json"] = json.dumps(intent.reasoning_trace)

        # Metadata
        if intent.metadata:
            pb_dict["metadata_json"] = json.dumps(intent.metadata)

        return pb_dict

    # ---- Severity Helpers ----------------------------------------------------

    @staticmethod
    def _severity_weight(severity: Severity) -> int:
        """Map severity to numeric weight for sorting."""
        weights = {
            Severity.LOW: 1,
            Severity.MEDIUM: 2,
            Severity.HIGH: 3,
            Severity.CRITICAL: 4,
        }
        return weights.get(severity, 0)


# ---------------------------------------------------------------------------
# Module entry-point for direct execution
# ---------------------------------------------------------------------------


def main() -> None:
    """Run the ConfigGenerator in demo mode with synthetic anomalies."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    generator = ConfigGenerator()

    # Create synthetic anomalies for demonstration
    anomalies = [
        Anomaly(
            element_id="eNB-001",
            anomaly_type=AnomalyType.RADIO_DEGRADATION,
            severity=Severity.HIGH,
            description="RSRP at -108 dBm, below -100 dBm threshold",
            confidence=0.85,
            metrics_snapshot={"metric": "rsrp", "value": -108.0, "threshold": -100.0},
        ),
        Anomaly(
            element_id="eNB-001",
            anomaly_type=AnomalyType.BEARER_FAILURE,
            severity=Severity.MEDIUM,
            description="Packet loss rate 0.08 exceeds 0.05 threshold",
            confidence=0.75,
            metrics_snapshot={
                "metric": "packet_loss_rate",
                "value": 0.08,
                "threshold": 0.05,
            },
        ),
    ]

    intent = generator.generate_intent(anomalies)

    print("=== Generated Intent ===")
    print(f"ID:           {intent.intent_id}")
    print(f"Category:     {intent.category}")
    print(f"Target:       {intent.target_element_id}")
    print(f"Confidence:   {intent.confidence_score:.3f}")
    print(f"Radio params: {json.dumps(intent.radio_params, indent=2)}")
    print(f"Core params:  {json.dumps(intent.core_params, indent=2)}")
    print(f"Rationale:\n{intent.rationale}")
    print(
        f"\nProtobuf dict:\n{json.dumps(generator.to_protobuf_dict(intent), indent=2)}"
    )


if __name__ == "__main__":
    main()
